### ISSUE TITLE
MySQL NDB Cluster Image

### ISSUE THREAD

**Issue by lstellway** [lstellway/magento2-docker-swarm#1]
Magento 2.2.0 now supports [MySQL NDB Cluster 7.4.x](https://dev.mysql.com/doc/mysql-cluster-excerpt/5.6/en/).

Notes:
  - Setup will include multiple services:
    - Master Service
    - Data Service
    - MySQL Service
  - [Video](https://www.youtube.com/watch?v=64jtbkuPtvc)

**Comment by brandontamm** [comment]
I ran across this article and tried to implement but I'm not quite as good as I thought :) Let me know if you are able to achieve this - https://www.percona.com/blog/2016/06/14/scaling-percona-xtradb-cluster-proxysql-docker-swarm/

**Comment by loganstellway** [comment]
Hi @brandontamm !

Thank you for this information! I will definitely refer to the resource if I move forward with this - it's nice to know that Percona also has a cluster solution. 

To be transparent: 
I have been spending time [learning Kubernetes](https://www.udacity.com/course/scalable-microservices-with-kubernetes--ud615) and plan to move forward with that as my cluster management tool. 

I am the only "tech" person at work, so I have been considering giving myself a break and utilizing a hosted database solution on a cloud provider such as [Google Cloud SQL](https://cloud.google.com/sql/) or [Amazon RDS](https://aws.amazon.com/rds/). 

I also thought it would be cool (and save money) to utilize a smaller cloud provider such as [DigitalOcean](https://www.digitalocean.com/) or [Vultr](https://www.vultr.com/) and just run a single instance of MySQL in the cluster. A high-availability MySQL deployment would be awesome, but (not being a database expert) I believe a single MySQL instance is performing just fine for our current needs. It will definitely be a necessity as we grow. With either solution, I would need to address other database management tasks such as backups / restores. 

TMI? Haha sorry for the brain dump.. I'll be sure to update you here if I have any magical MySQL moments

**Comment by loganstellway** [comment]
And while exploring [Percona's Docker Repository](https://github.com/percona/percona-docker), I came across [an Docker build file](https://github.com/percona/percona-docker/blob/master/pxb-24/Dockerfile) for [Percona XtraBackup](https://www.percona.com/software/mysql-database/percona-xtrabackup). Sounds like a promising solution for backups 😄
