### ISSUE TITLE
Redis Cluster

### ISSUE THREAD

**Issue by lstellway** [lstellway/magento2-docker-swarm#2]
Redis is not natively cluster-ready. 

Redis Documentation:
  - [Cluster Tutorial](https://redis.io/topics/cluster-tutorial)
  - [Cluster Specification](https://redis.io/topics/cluster-spec)
  - [Redis Sentinel](https://redis.io/topics/sentinel)
  - [AOF](https://redis.io/topics/persistence) (Append Only File mode)
    - Writes to disk to achieve data persistence

**Comment by loganstellway** [comment]
### Notes

Ports:
  - Client Port: 6379 (Default)
  - Cluster Bus: Client Port + 10,000 (16379)

[Cluster with Docker](https://redis.io/topics/cluster-tutorial#redis-cluster-and-docker) does not support [NATted environments](http://searchenterprisewan.techtarget.com/definition/Network-Address-Translation), but needs to utilize the [host network](https://docs.docker.com/engine/userguide/networking/#default-networks).
