### ISSUE TITLE
Share Media Across Server Nodes

### ISSUE THREAD

**Issue by lstellway** [lstellway/magento2-docker-swarm#7]
Magento allows users to upload media assets. How can uploaded assets be shared across server nodes in a clustered network?

**Comment by brandontamm** [comment]
I use digital ocean and they have block storage available ... currently only able to attach to a single node (or droplet) but the multi-mount capability is not far off and I am looking at using swarm but wanted to get a working swarm example of this setup and waiting for the block storage release.. found your repo so in my spare time (which is few) I will attempt to get this working.

**Comment by loganstellway** [comment]
Awesome, thanks @brandontamm!

A couple other thoughts I had about this:
  - Object Storage
    - Object storage could also be a nice solution (and less expensive). There are a couple existing Magento 2 projects I've seen for this. 
      - [thaiphan/magento2-s3](https://github.com/thaiphan/magento2-s3) - Amazon S3 integration for Magento 2
      - [bangerkuwranger/magento2-google-cloud-storage](https://github.com/bangerkuwranger/magento2-google-cloud-storage) - Google Cloud Storage for Magento 2
    - DigitalOcean has [Spaces](https://www.digitalocean.com/products/object-storage/) (object storage). The [Spaces API](https://developers.digitalocean.com/documentation/spaces/) is supposed to be [compatible with the Amason S3 API](https://developers.digitalocean.com/documentation/spaces/#aws-s3-compatibility).
